// <auto-generated />
namespace BenavidesFarm.DataModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMailConfigurationToJoinTeamSection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMailConfigurationToJoinTeamSection));
        
        string IMigrationMetadata.Id
        {
            get { return "201707020226405_AddMailConfigurationToJoinTeamSection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
