SET IDENTITY_INSERT [dbo].[Municipios] ON 

INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (1, N'Aguascalientes', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (2, N'Tijuana', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (3, N'Mexicali', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (4, N'Tecate', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (5, N'Puerto Peñasco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (6, N'Sn. Luis Río Colorado', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (7, N'Cd. Morelos', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (8, N'Ensenada', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (9, N'La Paz', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (10, N'Cd. Juárez', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (11, N'Delicias', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (12, N'Casas Grandes', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (13, N'Cuauhtémoc', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (14, N'Cd. Meoqui', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (15, N'Cd. Jiménez', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (16, N'Chihuahua', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (17, N'Del. Cuauhtémoc', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (18, N'Venustiano Carranza', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (19, N'Benito Juárez', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (20, N'Miguel Hidalgo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (21, N'Tlalpan', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (22, N'Azcapotzalco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (23, N'Cuajimalpa de Morelos', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (24, N'Alvaro Obregon', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (25, N'Gustavo A. Madero', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (26, N'Coyoacán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (27, N'Atizapán de Zaragoza', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (28, N'Iztapalapa', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (29, N'Naucalpan de Juárez', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (30, N'Xochimilco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (31, N'Piedras Negras', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (32, N'Monclova', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (33, N'Frontera', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (34, N'Saltillo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (35, N'Torreón', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (36, N'Acuña', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (37, N'Ramos Arizpe', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (38, N'Allende', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (39, N'Sabinas', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (40, N'Cd. Muzquiz', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (41, N'San Buenaventura', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (42, N'Parras', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (43, N'S. Pedro De Las Colonias', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (44, N'Nueva Rosita', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (45, N'Colima', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (46, N'Villa De Álvarez', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (47, N'Gómez Palacios', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (48, N'Durango', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (49, N'Cd. Lerdo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (50, N'Toluca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (51, N'Huixquilucan', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (52, N'Ixtapaluca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (53, N'Metepec', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (54, N'Tlalnepantla', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (55, N'Álvaro Obregón', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (56, N'San Pedro de los Pinos', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (57, N'TLALNEPANTLA DE BAZ', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (58, N'Cuautitlán Izcalli', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (59, N'Sn. Mateo Atenco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (60, N'Coacalco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (61, N'Ecatepec', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (62, N'Zinacantepec', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (63, N'Cuautitlan Izcalli', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (64, N'Texcoco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (65, N'Del. Nezahualcóyotl', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (66, N'Los Reyes Acaquilpan', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (67, N'León', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (68, N'Irapuato', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (69, N'Celaya', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (70, N'San Francisco del Rincón', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (71, N'Salamanca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (72, N'Acámbaro', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (73, N'Santa Ana', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (74, N'Valle De Santiago', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (75, N'Abasolo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (76, N'Manuel Doblado', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (77, N'Pueblo Nuevo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (78, N'Zihuatanejo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (79, N'Acapulco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (80, N'Guadalajara', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (81, N'Zapopan', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (82, N'Tlaquepaque', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (83, N'Tepatitlán de Morelos', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (84, N'Ciudad Guzmán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (85, N'Tonalá', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (86, N'Tlajomulco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (87, N'Enacarnación De Díaz', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (88, N'Bahia De Banderas', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (89, N'Puerto Vallarta', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (90, N'Ocotlán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (91, N'Chapala', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (92, N'Lago De Moreno', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (93, N'Tequila', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (94, N'Degollado', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (95, N'La Barca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (96, N'Atotonilco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (97, N'Zapotlanejo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (98, N'Ayotlán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (99, N'Tepatitlan De Morelos', NULL, NULL)

INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (100, N'Zamora', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (101, N'Morelia', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (102, N'La Piedad', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (103, N'Penjamo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (104, N'Yurecuaro', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (105, N'Tanhuato', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (106, N'Zacapu', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (107, N'Tangancícuaro', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (108, N'Pastor Ortiz', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (109, N'Penjamillo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (110, N'Puruándiro', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (111, N'Cuernavaca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (112, N'Tepic', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (113, N'Santiago Ixcuintla', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (114, N'Compostela', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (115, N'Cd. Guadalupe', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (116, N'Monterrey', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (117, N'Cadereyta Jiménez', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (118, N'Sn. Nicolás de los Garza', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (119, N'San Pedro Garza García', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (120, N'Linares', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (121, N'Sabinas Hgo.', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (122, N'Sta. Catarina', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (123, N'Apodaca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (124, N'Escobedo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (125, N'Montemorelos', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (126, N'Cerralvo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (127, N'Hidalgo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (128, N'China', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (129, N'Cd. Benito Juárez', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (130, N'Santiago', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (131, N'Ciénega de Flores', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (132, N'Galeana', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (133, N'General Terán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (134, N'García', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (135, N'Salinas Victoria', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (136, N'Zuazua', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (137, N'San Nicolas', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (138, N'Guadalupe', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (139, N'Cadereyta', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (140, N'Puebla', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (141, N'Querétaro', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (142, N'Cd. Valles', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (143, N'Matehuala', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (144, N'San Luis Potosí', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (145, N'Soledad De Graciano', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (146, N'Mochis', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (147, N'Guasave', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (148, N'Guamuchil', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (149, N'Navolato', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (150, N'Mazatlán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (151, N'Culiacán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (152, N'Ahome', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (153, N'Guaymas', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (154, N'Empalme', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (155, N'Cd. Obregón', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (156, N'Navojoa', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (157, N'Magadalena', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (158, N'Hermosillo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (159, N'Nogales', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (160, N'Huatabampo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (161, N'Caborca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (162, N'Esperanza', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (163, N'Cananea', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (164, N'Agua Prieta', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (165, N'San Luis Río Colorado', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (166, N'Obregón', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (167, N'Cd. Victoria', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (168, N'Tampico', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (169, N'Cd. Madero', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (170, N'Altamira', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (171, N'Mante', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (172, N'Pánuco', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (173, N'Reynosa', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (174, N'Aldama', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (175, N'Soto la Marina', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (176, N'Tantoyuca', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (177, N'Matamoros', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (178, N'Tula', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (179, N'Nvo. Laredo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (180, N'Tuxpan', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (181, N'Río Bravo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (182, N'Deleg. Nvo. Progreso', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (183, N'V. Hermoso', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (184, N'Miguel Alemán', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (185, N'Sn. Fdo.', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (186, N'Cd. Díaz Ordaz', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (187, N'Camargo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (188, N'Xicotencatl', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (189, N'Alamo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (190, N'Poza Rica', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (191, N'Tempoal', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (192, N'Boca del Río', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (193, N'Córdoba', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (194, N'Orizaba', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (195, N'Veracruz', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (196, N'Fresnillo', NULL, NULL)
INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (197, N'Zacatecas', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Municipios] OFF
