SET IDENTITY_INSERT [dbo].[Estados] ON 

INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (1, N'Aguascalientes', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (2, N'Baja California Norte', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (3, N'Sonora', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (4, N'Baja California Sur', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (5, N'Chihuahua', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (6, N'Ciudad de México', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (7, N'Estado de México', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (8, N'Coahuila', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (9, N'Colima', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (10, N'Durango', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (11, N'Guanajuato', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (12, N'Guerrero', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (13, N'Jalisco', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (14, N'Michoacán', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (15, N'Morelos', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (16, N'Nayarit', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (17, N'Nuevo León', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (18, N'Puebla', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (19, N'Querétaro', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (20, N'San Luis Potosí', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (21, N'Sinaloa', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (22, N'Tamaulipas', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (23, N'Veracruz', NULL, NULL)
INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (24, N'Zacatecas', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Estados] OFF
