//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenavidesFarm.DataModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlFileContainer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlFileContainer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BenavidesFarm.DataModels.SqlFileContainer", typeof(SqlFileContainer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT [dbo].[Branches] ON 
        ///
        ///INSERT [dbo].[Branches] ([BranchId], [BranchName], [BranchRegion], [BranchCeco], [BranchSap], [BranchAddress], [BranchCity], [BranchConsult], [BranchHour1], [BranchHour2], [BranchLongitude], [BranchLatitude], [BranchActive], [City_Id], [State_Id]) VALUES (1, N&apos;2L0074_Suc. Convención&apos;, NULL, N&apos;2L0074&apos;, NULL, NULL, NULL, 0, NULL, NULL, N&apos;-102.2709583&apos;, N&apos;21.87276389&apos;, 1, 1, 1)
        ///INSERT [dbo].[Branches] ([BranchId], [BranchName], [BranchRegion], [BranchCeco], [Branc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[Municipios] ON 
        ///
        ///INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (1, N&apos;Aguascalientes&apos;, NULL, NULL)
        ///INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (2, N&apos;Tijuana&apos;, NULL, NULL)
        ///INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (3, N&apos;Mexicali&apos;, NULL, NULL)
        ///INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (4, N&apos;Tecate&apos;, NULL, NULL)
        ///INSERT [dbo].[Municipios] ([Id], [Name], [Lng], [Lat]) VALUES (5, N&apos;Puerto Peñasco&apos;, NULL, NULL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT [dbo].[Estados] ON 
        ///
        ///INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (1, N&apos;Aguascalientes&apos;, NULL, NULL)
        ///INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (2, N&apos;Baja California Norte&apos;, NULL, NULL)
        ///INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (3, N&apos;Sonora&apos;, NULL, NULL)
        ///INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (4, N&apos;Baja California Sur&apos;, NULL, NULL)
        ///INSERT [dbo].[Estados] ([Id], [Name], [Lng], [Lat]) VALUES (5, N&apos;Chihuahua&apos;, NULL,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT [dbo].[EstadosMunicipios] ON 
        ///
        ///INSERT [dbo].[EstadosMunicipios] ([Id], [Estado_Id], [Municipio_Id]) VALUES (1, 1, 1)
        ///INSERT [dbo].[EstadosMunicipios] ([Id], [Estado_Id], [Municipio_Id]) VALUES (2, 2, 2)
        ///INSERT [dbo].[EstadosMunicipios] ([Id], [Estado_Id], [Municipio_Id]) VALUES (3, 2, 3)
        ///INSERT [dbo].[EstadosMunicipios] ([Id], [Estado_Id], [Municipio_Id]) VALUES (4, 2, 4)
        ///INSERT [dbo].[EstadosMunicipios] ([Id], [Estado_Id], [Municipio_Id]) VALUES (5, 2, 5)
        ///INSERT [dbo].[EstadosM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States_Cities {
            get {
                return ResourceManager.GetString("States_Cities", resourceCulture);
            }
        }
    }
}
